### ISSUE TITLE
geometry errors (mostly on norcham branch)

### ISSUE THREAD

**Issue by stefanix** [stefanix/LasaurGrbl#7]
Symptoms: gcode lines get dropped or scrambled leading to flattened curves and spikes in the cuts.

Suspicion: serial flow control and/or transmission buffers drop characters leading to lines being disregarded or inadvertenly changed

**Comment by stefanix** [comment]
New suspicion: The avr's serial port interrupt does not  get called on time because the stepper interrupt is fairly long. At 9600bps no other ISR may block for more than 104 microseconds ( this is 1664 instruction as one instruction takes 62.5ns@16MHz or probably less because of ISR overhead). At 57600bps this amounts to 17.3us or 277 instructions.

Will drop the bps and see if this helps ...

Find a good intro here:
https://binglongx.wordpress.com/2011/10/26/arduino-serial-port-communication/

**Comment by chamnit** [comment]
I've been studying up on interrupt functionality this weekend to track down a premature step end bug that I noticed when I plugged grbl into an oscilloscope for the first time (which has been fixed now.) The both stepper interrupts are very short and the long one can be interrupted by the serial rx/tx interrupts after the sei() command is called. Or at least it should. As far as I have noticed, the time for non-interruptible execution of the stepper interrupts is on the order of a 3 usecs.

**Comment by chamnit** [comment]
One more thing. I had a similar problem when I forgot that the serial ring buffer is one less than the defined size of 256, due to one of the bytes is used for tracking the beginning and end of the ring buffer. This one drove me nuts for a couple of days.

**Comment by stefanix** [comment]
In the rewrite of the flow control this got resolved.
